# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1034, 821)
        self.labImage = QtWidgets.QLabel(Dialog)
        # self.labImage.setGeometry(QtCore.QRect(20, 20, 531, 461))
        self.labImage.setObjectName("labImage")
        self.btnOpen = QtWidgets.QPushButton(Dialog)
        self.btnOpen.setGeometry(QtCore.QRect(30, 500, 93, 28))
        self.btnOpen.setObjectName("btnOpen")
        self.btnConvert = QtWidgets.QPushButton(Dialog)
        self.btnConvert.setGeometry(QtCore.QRect(140, 500, 131, 31))
        self.btnConvert.setObjectName("btnConvert")
        self.btnSave = QtWidgets.QPushButton(Dialog)
        self.btnSave.setGeometry(QtCore.QRect(290, 500, 93, 28))
        self.btnSave.setObjectName("btnSave")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.labImage.setText(_translate("Dialog", "TextLabel"))
        self.btnOpen.setText(_translate("Dialog", "Open"))
        self.btnConvert.setText(_translate("Dialog", "Convert image"))
        self.btnSave.setText(_translate("Dialog", "Save"))

